### ISSUE TITLE
What does "a knockoff bad coverflow implementation in Flutter" mean?

### ISSUE THREAD

**Issue by dmjones** [efortuna/coverflow#4]
This looks like a useful library, but the self-deprecating description is a little worrying.

Is there anything specific you can point to which would render this library unsuitable for production use? Or are you just too modest? :-)

**Comment by efortuna** [comment]
No, there's no reason you shouldn't use this for production use. I mostly meant that it was just a very basic implementation and was being self-deprecating. I'll remove that part of the description
