### ISSUE TITLE
update dart package

### ISSUE THREAD

**Issue by bluemix** [efortuna/coverflow#8]
currently, the last [update](https://pub.dartlang.org/packages/simple_coverflow#-versions-tab-) is on April. 
i hope to update it with the latest changes, 
so that people can see the new changes.
thanks in advance for this library 👍 

<img width="701" alt="screen shot 2018-12-16 at 21 28 17" src="https://user-images.githubusercontent.com/3332274/50057304-88d76980-0179-11e9-8a78-23bc2f865d7f.png">

**Comment by efortuna** [comment]
Thanks for the nudge! I forgot I hadn't updated it. It's there now! 0.0.7!
